In [11]:
import pandas as pd
import numpy as np

In [12]:
filepath = "../data/merged_training_ps1.csv"
compfilepath = "../data/training/training_data.csv"

In [13]:
comp_df = pd.read_csv(compfilepath)
comp_df

,distance,objid,ra,dec,cModelMag_u,cModelMag_g,cModelMag_r,cModelMag_i,cModelMag_z,cModelMagErr_u,...,extinction_r,extinction_i,extinction_z,sdss_photo_redshift,sdss_photo_redshift_error,photoErrorClass,specObjID,spec_redshift,spec_redshift_error,zWarning
0,2026.539017,1237652899137716382,0.517111,-11.227261,19.58707,18.18890,17.05650,16.56595,16.37477,0.084959,...,0.092044,0.068399,0.050876,0.182284,0.016348,1,731859439535024128,0.171190,0.000023,0
1,2027.543966,1237652899137716389,0.523533,-11.210584,18.06274,17.01967,16.48803,16.13283,16.24654,0.040734,...,0.092201,0.068515,0.050963,0.071149,0.014432,1,731858889779210240,0.055941,0.000015,0
2,2027.756827,1237652899137716363,0.434286,-11.206105,20.02411,18.95177,17.70889,17.19174,16.99660,0.209637,...,0.090968,0.067599,0.050281,0.222290,0.011455,1,731858614901303296,0.231475,0.000045,0
3,2027.981282,1237652899137585233,0.200071,-11.200748,19.09781,18.45833,18.29535,17.94884,18.06034,0.043539,...,0.078588,0.058399,0.043438,0.087326,0.016473,-1,731873458308278272,0.105967,0.000005,0
4,2028.166817,1237652899137585244,0.228195,-11.197786,19.58003,18.08033,17.37261,16.96439,16.63410,0.061606,...,0.079545,0.059110,0.043967,0.102634,0.022706,1,731868510505953280,0.119121,0.000011,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363347,3599.979474,1237678777386992426,320.260317,3.464909,23.13773,20.78700,19.00083,18.48276,18.19419,0.703699,...,0.146716,0.109026,0.081095,0.351290,0.017866,1,4590337990606477312,0.325870,0.000052,0
363348,3599.980837,1237678825169093426,320.445810,3.577936,23.87643,21.26208,19.31467,18.75938,18.31378,1.429815,...,0.130134,0.096704,0.071930,0.362257,0.027636,1,4590315725496014848,0.345263,0.000055,0
363349,3599.981646,1237678847722259055,331.451645,9.206092,18.71547,18.74028,17.70879,17.19762,16.87132,0.114985,...,0.119197,0.088576,0.065884,0.226118,0.024551,1,5705172693848184832,0.209752,0.000023,0
363350,3599.987979,1237669761717567975,322.551644,4.817705,24.67046,22.15823,20.41234,19.31928,18.78454,1.481043,...,0.142263,0.105717,0.078634,0.548578,0.026267,1,4593903433782941696,0.521608,0.000093,0
363351,3599.992325,1237678847722587435,332.089685,9.469888,18.13422,22.90122,21.40718,20.01662,18.60597,0.285261,...,0.129670,0.096359,0.071673,0.666442,0.048729,3,5703941790547335168,0.666277,0.000296,0

In [14]:
df = pd.read_csv(filepath)
comp_df = pd.read_csv(compfilepath)
comp_df = comp_df[['ra', 'dec', 'spec_redshift', 'spec_redshift_error', 'zWarning']]

# df = df[['objID','raMean', 'decMean', 'gMeanKronMag', 'rMeanKronMag', 'iMeanKronMag', 'zMeanKronMag', 'yMeanKronMag', 'gMeanKronMagErr', 'rMeanKronMagErr', 'iMeanKronMagErr', 'zMeanKronMagErr', 'yMeanKronMagErr', 'orig_ra', 'orig_dec']]
df = pd.merge(df, comp_df, left_on=['orig_ra', 'orig_dec'], right_on=['ra', 'dec'], how='left')
df.drop(columns=['ra', 'dec'], inplace=True)

In [15]:
df

,objName,objAltName1,objAltName2,objAltName3,objID,uniquePspsOBid,ippObjID,surveyID,htmID,zoneID,...,yMeanApMagErr,yMeanApMagStd,yMeanApMagNpt,yFlags,distance,orig_ra,orig_dec,spec_redshift,spec_redshift_error,zWarning
0,PSO J000.5235-11.2106,-999,-999,-999,94540005235167647,3481158000056745,402734788435369,0,8856249151208,9454,...,0.031417,0.120627,13,16892216,0.000023,0.523533,-11.210584,0.055941,0.000015,0
1,PSO J000.4343-11.2061,-999,-999,-999,94550004342113056,3481158000045417,402734788424040,0,8856248491429,9455,...,0.029417,0.063244,10,16892216,0.000005,0.434286,-11.206105,0.231475,0.000045,0
2,PSO J000.2280-11.1977,-999,-999,-999,94560002278813358,3481158000022534,402734788401157,0,8856237677502,9456,...,-999.000000,-999.000000,0,0,0.000208,0.228195,-11.197786,0.119121,0.000011,0
3,PSO J000.2001-11.2007,-999,-999,-999,94550002001139464,3481158000019847,402734788398470,0,8856238139639,9455,...,0.095257,0.320047,8,16892216,0.000008,0.200071,-11.200748,0.105967,0.000005,0
4,PSO J000.5171-11.2273,-999,-999,-999,94520005171187668,3481158000055778,402734788434402,0,8856249614212,9452,...,0.022522,0.047697,10,16892216,0.000022,0.517111,-11.227261,0.171190,0.000023,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362616,PSO J320.2603+03.4649,-999,-999,-999,112153202603208356,3590436000014074,79439715120889,0,13345830767086,11215,...,0.041888,0.186926,12,16892216,0.000008,320.260317,3.464909,0.325870,0.000052,0
362617,PSO J320.4458+03.5779,-999,-999,-999,112293204457183994,3590436000038857,79439715145674,0,13347733187210,11229,...,0.051289,0.332401,13,16892216,0.000026,320.445810,3.577936,0.345263,0.000055,0
362618,PSO J331.4516+09.2061,-999,-999,-999,119043314516567798,3595309000022562,121070833129506,0,13386417215404,11904,...,0.082822,0.233960,10,16892216,0.000024,331.451645,9.206092,0.209752,0.000023,0
362619,PSO J322.5516+04.8177,-999,-999,-999,113783225516251705,3567071000008059,79890686680955,0,13344814799932,11378,...,0.060578,0.214376,10,16892216,0.000013,322.551644,4.817705,0.521608,0.000093,0
362620,PSO J332.0897+09.4699,-999,-999,-999,119363320895914446,3595307000047013,120954869036968,0,13386780131590,11936,...,0.065196,0.128719,4,16892216,0.000035,332.089685,9.469888,0.666277,0.000296,0

In [16]:
df.to_csv(filepath)