In [140]:
import glob
import pandas as pd
df = pd.read_csv('../all_sample_sorted_by_o_with_classification(close companion).csv')

In [141]:
tg_list = [f'../data/catalog/ps1/redshift/origin/t{ra:08.4f}{dec:+07.4f}.csv'for ra, dec in zip(df.paliya_RA, df.paliya_DEC)]

In [142]:
import numpy as np
cat_list = np.array(glob.glob('../data/catalog/ps1/redshift/origin/*.csv'))
mask = np.array([i in tg_list for i in cat_list])

In [143]:
cat_list = cat_list[mask]

In [144]:
df_close = pd.DataFrame(columns = pd.read_csv(cat_list[0]).sort_values(by='distance').head(1)[['distance', 'raMean', 'decMean', 'z_phot', 'z_phot_err', 'Absolute_Mag_r']].columns)
for i in range(len(cat_list)):
    df_close.loc[i] = pd.read_csv(cat_list[i]).sort_values(by='distance').iloc[0][['distance', 'raMean', 'decMean', 'z_phot', 'z_phot_err', 'Absolute_Mag_r']]

In [145]:
df = pd.concat([df, df_close], axis = 1)

In [146]:
df

,paliya_RA,paliya_DEC,paliya_Z,distance,raMean,decMean,z_phot,z_phot_err,Absolute_Mag_r
0,4.264051,-4.789808,0.098000,1.064782,4.246856,-4.794426,0.351036,0.063251,-20.664897
1,6.079566,-1.638201,0.038000,0.000611,6.079567,-1.638211,0.094779,0.017759,-23.526417
2,8.159169,-1.009781,0.091725,0.001908,8.159173,-1.009812,0.073261,0.023740,-20.282622
3,17.537560,-10.145390,0.057938,0.002119,17.537557,-10.145425,0.057401,0.013338,-21.392987
4,19.813820,30.321460,0.051302,0.001174,19.813803,30.321447,0.087920,0.024501,-21.229338
...,...,...,...,...,...,...,...,...,...
113,334.543000,28.766200,0.087515,0.002696,334.542949,28.766206,0.061942,0.032383,-20.370257
114,336.680300,27.274310,0.099000,0.001114,336.680279,27.274309,0.078420,0.017074,-20.921141
115,342.102700,0.155776,0.053784,0.004099,342.102640,0.155743,0.062022,0.014910,-21.214043
116,343.717600,0.775379,0.091000,0.209718,343.714282,0.776479,0.077739,0.014507,-20.778719
117,347.373200,19.927540,0.087818,0.004849,347.373114,19.927544,0.152331,0.031823,-21.592931

In [147]:
tg_list = [f'../data/catalog/ps1/redshift_xgb/origin/t{ra:08.4f}{dec:+07.4f}.csv'for ra, dec in zip(df.paliya_RA, df.paliya_DEC)]

In [148]:
import numpy as np
cat_list = np.array(glob.glob('../data/catalog/ps1/redshift_xgb/origin/*.csv'))
mask = np.array([i in tg_list for i in cat_list])

In [149]:
cat_list = cat_list[mask]

In [150]:
df_close = pd.DataFrame(columns = ['z_phot_xgb', 'z_phot_err_xgb'])
for i in range(len(cat_list)):
    tmp = pd.read_csv(cat_list[i]).sort_values(by='distance').iloc[0][['z_phot', 'z_phot_err']]
    tmp.rename({'z_phot':'z_phot_xgb', 'z_phot_err':'z_phot_err_xgb'}, inplace = True)
    df_close.loc[i] = tmp

In [151]:
df = pd.concat([df, df_close], axis=1)

In [152]:
df

,paliya_RA,paliya_DEC,paliya_Z,distance,raMean,decMean,z_phot,z_phot_err,Absolute_Mag_r,z_phot_xgb,z_phot_err_xgb
0,4.264051,-4.789808,0.098000,1.064782,4.246856,-4.794426,0.351036,0.063251,-20.664897,0.392628,0.109292
1,6.079566,-1.638201,0.038000,0.000611,6.079567,-1.638211,0.094779,0.017759,-23.526417,0.112671,0.061033
2,8.159169,-1.009781,0.091725,0.001908,8.159173,-1.009812,0.073261,0.023740,-20.282622,0.093705,0.026202
3,17.537560,-10.145390,0.057938,0.002119,17.537557,-10.145425,0.057401,0.013338,-21.392987,0.055090,0.014027
4,19.813820,30.321460,0.051302,0.001174,19.813803,30.321447,0.087920,0.024501,-21.229338,0.089413,0.024189
...,...,...,...,...,...,...,...,...,...,...,...
113,334.543000,28.766200,0.087515,0.002696,334.542949,28.766206,0.061942,0.032383,-20.370257,0.076351,0.030693
114,336.680300,27.274310,0.099000,0.001114,336.680279,27.274309,0.078420,0.017074,-20.921141,0.080865,0.022436
115,342.102700,0.155776,0.053784,0.004099,342.102640,0.155743,0.062022,0.014910,-21.214043,0.056256,0.016757
116,343.717600,0.775379,0.091000,0.209718,343.714282,0.776479,0.077739,0.014507,-20.778719,0.080526,0.019340
117,347.373200,19.927540,0.087818,0.004849,347.373114,19.927544,0.152331,0.031823,-21.592931,0.133894,0.045467

In [153]:
df.to_csv('../all_sample_sorted_by_o_with_classification(close companion).csv')